### ISSUE TITLE
Keep Alive not working

### ISSUE THREAD

**Issue by lorenesta** [apifytech/proxy-chain#44]
I'm using this awesome project to proxy certains requests and I noticed that keep alive doesn't work. Is there a way to make it work?

**Comment by jancurn** [comment]
Please, can you provide more details about what you're doing, what you see and what should be the expected behavior? BTW, `Keep-Alive` is not so-called hop-by-hop header, which means that the proxies are not obliged to forward it - see https://github.com/apifytech/proxy-chain/blob/master/src/tools.js#L35

**Comment by jancurn** [comment]
Please try to use the latest release, it has slightly different handling of `Keep-Alive` messages. Closing this for now.
